- name: crear máquina de laboratorio
  hosts: localhost
  vars_files:
    - env_vars/aws_vault.yml
    - env_vars/traineeid.yml

  tasks:
    - name: crear vm's en cloud
      ec2:
        key_name: "{{ aws_keypair_name }}"
        group:
            - "ENABLE_SSH_ANSIBLE_COURSE"
        aws_secret_key: "{{ aws_secret }}"
        aws_access_key: "{{ aws_access }}"
        region: "eu-west-1"
        instance_tags:
            Name: "{{ item }}"
            Curso: "ansible"
        instance_type: "t2.nano"
        image: "{{ aws_ec2_ami }}"
        vpc_subnet_id: "{{ aws_ec2_subnet }}"
        count_tag:
            Name: "{{ item }}"
        exact_count: 1
        assign_public_ip: yes
        wait: yes
      register: ec2_instances
      with_items:
        - "pokemon_pikachu"

    - name: vaciamos inventario lab
      shell: 'echo "" > inventories/laboratorio.txt'

    - name: guardamos las ip's en inventario
      shell: "echo {{ item.instances[0].public_ip }} >> inventories/laboratorio.txt"
      with_items: '{{ ec2_instances.results }}'

